---

- name: Create Group
  group:
    name: "{{ couchpotato_group }}"
    system: no
    state: present 
  become: true

- name: Create User
  user:
    name: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    state: present
    system: no
    createhome: no
    shell: /bin/false
  become: true

- name: Create dirs 
  file:
    path: "{{ item }}"
    owner: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ couchpotato_install_dir }}"
    - "{{ couchpotato_config_dir }}"
    - "{{ couchpotato_script_dir }}"
  become: true

- name: Clone repo from GitHub
  git:
    repo: "{{ couchpotato_git_repo }}"
    dest: "{{ couchpotato_install_dir }}"
    version: master

- name: Take Ownership of Git Repo
  file:
    path: "{{ couchpotato_install_dir }}"
    owner: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    recurse: true
  become: true

- block:

    - name: Get files from couchpotato_backup_target
      find:
        paths: "{{ couchpotato_backup_target }}"
      register: found_files

    - name: Get latest backup file
      set_fact:
        __couchpotato_restore_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first  }}"

    - name: Set Fact for couchpotato_restore_file
      set_fact:
        couchpotato_restore_file: "{{ __couchpotato_restore_file.path }}"

  when: couchpotato_restore_from_backups

- name: Extract Restore Backup
  unarchive:
    src: "{{ couchpotato_restore_file }}"
    dest: "{{ couchpotato_config_dir }}"
    copy: no
    owner: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
  become: yes
  when:
    - couchpotato_restore_file is defined

- name: Set dir owner
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    mode: 0755
  with_items:
    - "{{ couchpotato_install_dir }}"
    - "{{ couchpotato_config_dir }}"

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=5050/tcp  # HTTP port
    - firewall-cmd --permanent --add-port=5222/tcp  # HTTPS port
    - firewall-cmd --reload
  become: yes
  when: firewall_enabled

- name: Post Processing Script Template
  template:
    src: couchpotato_post_processor.sh.j2
    dest: "{{ couchpotato_script_dir }}"
    owner: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    mode: 0644

- name: Add service
  template:
    src: couchpotato.service.j2
    dest: /etc/systemd/system/couchpotato.service
    owner: root
    group: root
    mode: 0644

- name: Enable service
  service:
    name: couchpotato.service
    enabled: yes
    state: started
