---

- name: Create Group
  group:
    name: "{{ couchpotato_group }}"
    system: no
    state: present 
  become: true

- name: Create User
  user:
    name: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    state: present
    system: no
    createhome: no
    shell: /bin/false
  become: true

- name: Create dirs 
  file:
    path: "{{ item }}"
    owner: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ couchpotato_install_dir }}"
    - "{{ couchpotato_config_dir }}"
  become: true

- name: Clone repo from GitHub
  git:
    repo: "{{ couchpotato_git_repo }}"
    dest: "{{ couchpotato_install_dir }}"
    version: master

- name: Copy Restore File (From Locall if possible)
  copy:
    src: "{{ playbook_dir }}/files/couchpotato_backup.tar.gz"
    dest: /tmp/couchpotato_backup.tar.gz
    remote_src: no
  when: couchpotato_restore_file is defined
  ignore_errors: yes

- name: Stat Restore File
  stat: path="\tmp\couchpotato_backup.tar.gz"
  register: restore_file

- name: Copy Restore File
  copy:
    src: "{{ playbook_dir }}/files/couchpotato_backup.tar.gz"
    dest: /tmp
  when:
    - couchpotato_restore_file is defined
    - not restore_file.stat.exists

- name: Extract Restore Backup
  unarchive:
    src: "/tmp/couchpotato_backup.tar.gz"
    dest: "{{ couchpotato_config_dir }}"
    copy: no
  become: yes
  when:
    - couchpotato_restore_file is defined

- name: Set dir owner
  file:
    path: "{{ item }}"
    owner: "{{ couchpotato_user }}"
    group: "{{ couchpotato_group }}"
    recurse: yes
    state: directory
    mode: 0755
  with_items:
    - "{{ couchpotato_install_dir }}"
    - "{{ couchpotato_config_dir }}"

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=5050/tcp  # HTTP port
    - firewall-cmd --permanent --add-port=5222/tcp  # HTTPS port
    - firewall-cmd --reload
  become: yes
  when: firewall_enabled

- name: Add service
  template:
    src: couchpotato.service.j2
    dest: /etc/systemd/system/couchpotato.service
    owner: root
    group: root
    mode: 0644

- name: Enable service
  service:
    name: couchpotato.service
    enabled: yes
    state: started