---
- name: Check if installed
  stat: path={{ couchpotato_install_dir }}
  register: check_installed

- name: Install
  include: 'install.yml'
  when: not check_installed.stat.exists

- name: Configure Backups
  include: 'backups.yml'
  when: couchpotato_cron_backup_enabled

- block:

    - name: Update
      git:
        repo: "{{ couchpotato_git_repo }}"
        dest: "{{ couchpotato_install_dir }}"
        version: master
        update: yes
      ignore_errors: true
      
    - name: Take Ownership of Git Repo
      file:
        path: "{{ couchpotato_install_dir }}"
        owner: "{{ couchpotato_user }}"
        group: "{{ couchpotato_group }}"
        recurse: true
      become: true
      notify:
        - restart couchpotato

  when:
    - check_installed.stat.exists
    - couchpotato_allow_update
